/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControleMenu;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextArea;
import model.Cliente;

/**
 *
 * @author Micro
 */
public class Menu extends javax.swing.JFrame {
    private ControleMenu c; // Declara o nosso cérebro
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    private Cliente cliente;

    /**
     * Creates new form Menu
     */
    public Menu(Cliente cliente) {
        initComponents();
        this.c = new ControleMenu(this, cliente); // Inicializa o cérebro
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelLanche = new javax.swing.JPanel();
        painelDestaqueAlimento = new javax.swing.JLabel();
        painelPrecoAlimento = new javax.swing.JLabel();
        scrollCardapio = new javax.swing.JScrollPane();
        painelDescAlimento = new javax.swing.JTextArea();
        btnAdicionar = new javax.swing.JButton();
        painelTituloAlimento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblPizzas = new javax.swing.JLabel();
        imgPizza15 = new javax.swing.JLabel();
        imgPizza11 = new javax.swing.JLabel();
        imgPizza12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imgBurguer11 = new javax.swing.JLabel();
        imgBurguer12 = new javax.swing.JLabel();
        imgBurguer13 = new javax.swing.JLabel();
        imgBurguer15 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        imgPizza13 = new javax.swing.JLabel();
        lblLanches = new javax.swing.JLabel();
        imgPizza14 = new javax.swing.JLabel();
        lblBebidas = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        imgAcomp11 = new javax.swing.JLabel();
        lblBebidas1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        imgAcomp12 = new javax.swing.JLabel();
        imgBebida11 = new javax.swing.JLabel();
        imgBebida12 = new javax.swing.JLabel();
        imgBebida13 = new javax.swing.JLabel();
        imgBebida14 = new javax.swing.JLabel();
        imgBebida15 = new javax.swing.JLabel();
        btnGerarPedido = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("cardapio");
        setBackground(new java.awt.Color(234, 168, 0));
        setForeground(new java.awt.Color(255, 102, 51));
        setSize(new java.awt.Dimension(814, 679));

        painelLanche.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelLanche.setLayout(null);

        painelDestaqueAlimento.setBackground(new java.awt.Color(255, 255, 255));
        painelDestaqueAlimento.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelLanche.add(painelDestaqueAlimento);
        painelDestaqueAlimento.setBounds(40, 10, 280, 240);

        painelPrecoAlimento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        painelPrecoAlimento.setForeground(new java.awt.Color(0, 0, 0));
        painelLanche.add(painelPrecoAlimento);
        painelPrecoAlimento.setBounds(10, 290, 280, 40);

        painelDescAlimento.setEditable(false);
        painelDescAlimento.setColumns(20);
        painelDescAlimento.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        painelDescAlimento.setForeground(new java.awt.Color(0, 0, 0));
        painelDescAlimento.setLineWrap(true);
        painelDescAlimento.setRows(5);
        painelDescAlimento.setWrapStyleWord(true);
        painelDescAlimento.setBorder(null);
        scrollCardapio.setViewportView(painelDescAlimento);

        painelLanche.add(scrollCardapio);
        scrollCardapio.setBounds(40, 330, 280, 280);

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        painelLanche.add(btnAdicionar);
        btnAdicionar.setBounds(90, 630, 183, 30);

        painelTituloAlimento.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        painelTituloAlimento.setForeground(new java.awt.Color(0, 0, 0));
        painelLanche.add(painelTituloAlimento);
        painelTituloAlimento.setBounds(10, 260, 280, 60);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        lblPizzas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblPizzas.setForeground(new java.awt.Color(0, 0, 0));
        lblPizzas.setText("PIZZAS");

        imgPizza15.setBackground(new java.awt.Color(255, 204, 0));
        imgPizza15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        imgPizza15.setForeground(new java.awt.Color(255, 255, 255));
        imgPizza15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pbrocolis.png"))); // NOI18N
        imgPizza15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Brócolis & Alho", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N
        imgPizza15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgPizza15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgPizza15MouseClicked(evt);
            }
        });

        imgPizza11.setBackground(new java.awt.Color(255, 204, 0));
        imgPizza11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imgPizza11.setForeground(new java.awt.Color(255, 255, 255));
        imgPizza11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pcalabresa.png"))); // NOI18N
        imgPizza11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calabresa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        imgPizza11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgPizza11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgPizza11MouseClicked(evt);
            }
        });

        imgPizza12.setBackground(new java.awt.Color(255, 204, 0));
        imgPizza12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        imgPizza12.setForeground(new java.awt.Color(255, 255, 255));
        imgPizza12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/p4queijos.png"))); // NOI18N
        imgPizza12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Quatro Queijos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N
        imgPizza12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgPizza12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgPizza12MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cardápio");

        imgBurguer11.setBackground(new java.awt.Color(255, 204, 0));
        imgBurguer11.setForeground(new java.awt.Color(255, 255, 255));
        imgBurguer11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/xburguer.jpg"))); // NOI18N
        imgBurguer11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "X-Burguer", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        imgBurguer11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgBurguer11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBurguer11MouseClicked(evt);
            }
        });

        imgBurguer12.setForeground(new java.awt.Color(255, 255, 255));
        imgBurguer12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/xsalada.jpg"))); // NOI18N
        imgBurguer12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "X-Salada", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        imgBurguer12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgBurguer12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBurguer12MouseClicked(evt);
            }
        });

        imgBurguer13.setForeground(new java.awt.Color(255, 255, 255));
        imgBurguer13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/xfrango.png"))); // NOI18N
        imgBurguer13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "X-Frango", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        imgBurguer13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgBurguer13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBurguer13MouseClicked(evt);
            }
        });

        imgBurguer15.setForeground(new java.awt.Color(255, 255, 255));
        imgBurguer15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/xbacon.png"))); // NOI18N
        imgBurguer15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "X-Bacon Duplo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N
        imgBurguer15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgBurguer15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBurguer15MouseClicked(evt);
            }
        });

        imgPizza13.setBackground(new java.awt.Color(255, 204, 0));
        imgPizza13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        imgPizza13.setForeground(new java.awt.Color(255, 255, 255));
        imgPizza13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pfrango.png"))); // NOI18N
        imgPizza13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Frango & Catupiry", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 10))); // NOI18N
        imgPizza13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgPizza13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgPizza13MouseClicked(evt);
            }
        });

        lblLanches.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLanches.setForeground(new java.awt.Color(0, 0, 0));
        lblLanches.setText("LANCHES");

        imgPizza14.setBackground(new java.awt.Color(255, 204, 0));
        imgPizza14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        imgPizza14.setForeground(new java.awt.Color(255, 255, 255));
        imgPizza14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pportuguesa.png"))); // NOI18N
        imgPizza14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Portuguesa", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        imgPizza14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgPizza14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgPizza14MouseClicked(evt);
            }
        });

        lblBebidas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBebidas.setForeground(new java.awt.Color(0, 0, 0));
        lblBebidas.setText("ACOMPANHAMENTOS");

        imgAcomp11.setBackground(new java.awt.Color(255, 204, 0));
        imgAcomp11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imgAcomp11.setForeground(new java.awt.Color(255, 255, 255));
        imgAcomp11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/batatafrita.png"))); // NOI18N
        imgAcomp11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Batata Frita P", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N
        imgAcomp11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgAcomp11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgAcomp11MouseClicked(evt);
            }
        });

        lblBebidas1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBebidas1.setForeground(new java.awt.Color(0, 0, 0));
        lblBebidas1.setText("BEBIDAS");

        imgAcomp12.setBackground(new java.awt.Color(255, 204, 0));
        imgAcomp12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imgAcomp12.setForeground(new java.awt.Color(255, 255, 255));
        imgAcomp12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/batatafritag.png"))); // NOI18N
        imgAcomp12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Batata Frita G", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N
        imgAcomp12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgAcomp12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgAcomp12MouseClicked(evt);
            }
        });

        imgBebida11.setBackground(new java.awt.Color(255, 204, 0));
        imgBebida11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imgBebida11.setForeground(new java.awt.Color(255, 255, 255));
        imgBebida11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cocacola.png"))); // NOI18N
        imgBebida11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coca-Cola", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        imgBebida11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgBebida11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBebida11MouseClicked(evt);
            }
        });

        imgBebida12.setBackground(new java.awt.Color(255, 204, 0));
        imgBebida12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imgBebida12.setForeground(new java.awt.Color(255, 255, 255));
        imgBebida12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cocacolazero.png"))); // NOI18N
        imgBebida12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Coca Zero", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        imgBebida12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgBebida12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBebida12MouseClicked(evt);
            }
        });

        imgBebida13.setBackground(new java.awt.Color(255, 204, 0));
        imgBebida13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imgBebida13.setForeground(new java.awt.Color(255, 255, 255));
        imgBebida13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/guarana.png"))); // NOI18N
        imgBebida13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Guaraná", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 14))); // NOI18N
        imgBebida13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgBebida13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBebida13MouseClicked(evt);
            }
        });

        imgBebida14.setBackground(new java.awt.Color(255, 204, 0));
        imgBebida14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imgBebida14.setForeground(new java.awt.Color(255, 255, 255));
        imgBebida14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/sucolaranja.png"))); // NOI18N
        imgBebida14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suco de Laranja", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 10))); // NOI18N
        imgBebida14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgBebida14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBebida14MouseClicked(evt);
            }
        });

        imgBebida15.setBackground(new java.awt.Color(255, 204, 0));
        imgBebida15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imgBebida15.setForeground(new java.awt.Color(255, 255, 255));
        imgBebida15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cerveja.png"))); // NOI18N
        imgBebida15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cerveja Long-Neck", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Comic Sans MS", 1, 10))); // NOI18N
        imgBebida15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        imgBebida15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgBebida15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBebida15)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBebidas1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imgBebida11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgBebida12)
                        .addGap(12, 12, 12)
                        .addComponent(imgBebida13)
                        .addGap(12, 12, 12)
                        .addComponent(imgBebida14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imgAcomp11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgAcomp12))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBebidas)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPizzas)
                        .addComponent(lblLanches)
                        .addComponent(jLabel1)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(imgBurguer11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(imgBurguer12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(imgBurguer13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(imgBurguer15))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(imgPizza11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imgPizza15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(12, 12, 12)
                            .addComponent(imgPizza12, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(imgPizza13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(imgPizza14))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(lblLanches)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBurguer11)
                    .addComponent(imgBurguer12)
                    .addComponent(imgBurguer15)
                    .addComponent(imgBurguer13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPizzas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(imgPizza14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(imgPizza13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgPizza12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imgPizza11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(imgPizza15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(lblBebidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgAcomp11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgAcomp12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBebidas1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgBebida11, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgBebida12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgBebida13, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgBebida14, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imgBebida15, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );

        jScrollPane2.setViewportView(jPanel1);

        btnGerarPedido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnGerarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnGerarPedido.setText(" Gerar Pedido");
        btnGerarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGerarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarPedidoActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGerarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelLanche, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerarPedido)
                    .addComponent(btnVoltar))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(painelLanche, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Logado logado = new Logado(this.cliente);
        logado.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnGerarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGerarPedidoActionPerformed

    private void imgBurguer11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBurguer11MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("X-Burger");
    }//GEN-LAST:event_imgBurguer11MouseClicked

    private void imgBurguer12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBurguer12MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("X-Salada");
    }//GEN-LAST:event_imgBurguer12MouseClicked

    private void imgBurguer15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBurguer15MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("X-Bacon Duplo");
    }//GEN-LAST:event_imgBurguer15MouseClicked

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void imgPizza11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPizza11MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("Pizza de Calabresa");
    }//GEN-LAST:event_imgPizza11MouseClicked

    private void imgPizza12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPizza12MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("Pizza Quatro Queijos");
    }//GEN-LAST:event_imgPizza12MouseClicked

    private void imgPizza13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPizza13MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("Pizza de Frango com Catupiry");
    }//GEN-LAST:event_imgPizza13MouseClicked

    private void imgPizza14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPizza14MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("Pizza Portuguesa");
    }//GEN-LAST:event_imgPizza14MouseClicked

    private void imgPizza15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPizza15MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("Pizza de Brócolis com Alho");
    }//GEN-LAST:event_imgPizza15MouseClicked

    private void imgAcomp11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgAcomp11MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("Batata Frita Pequena");
    }//GEN-LAST:event_imgAcomp11MouseClicked

    private void imgBurguer13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBurguer13MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("X-Frango");
    }//GEN-LAST:event_imgBurguer13MouseClicked

    private void imgAcomp12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgAcomp12MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("Batata Frita Grande");
    }//GEN-LAST:event_imgAcomp12MouseClicked

    private void imgBebida11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBebida11MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("Coca-Cola");
    }//GEN-LAST:event_imgBebida11MouseClicked

    private void imgBebida12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBebida12MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("Coca-Cola Zero");
    }//GEN-LAST:event_imgBebida12MouseClicked

    private void imgBebida13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBebida13MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("Guaraná Antarctica");
    }//GEN-LAST:event_imgBebida13MouseClicked

    private void imgBebida14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBebida14MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("Suco de Laranja Natural");
    }//GEN-LAST:event_imgBebida14MouseClicked

    private void imgBebida15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgBebida15MouseClicked
        // TODO add your handling code here:
        c.exibirDetalhes("Cerveja Long Neck");
    }//GEN-LAST:event_imgBebida15MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnGerarPedido;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel imgAcomp11;
    private javax.swing.JLabel imgAcomp12;
    private javax.swing.JLabel imgBebida11;
    private javax.swing.JLabel imgBebida12;
    private javax.swing.JLabel imgBebida13;
    private javax.swing.JLabel imgBebida14;
    private javax.swing.JLabel imgBebida15;
    private javax.swing.JLabel imgBurguer11;
    private javax.swing.JLabel imgBurguer12;
    private javax.swing.JLabel imgBurguer13;
    private javax.swing.JLabel imgBurguer15;
    private javax.swing.JLabel imgPizza11;
    private javax.swing.JLabel imgPizza12;
    private javax.swing.JLabel imgPizza13;
    private javax.swing.JLabel imgPizza14;
    private javax.swing.JLabel imgPizza15;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBebidas;
    private javax.swing.JLabel lblBebidas1;
    private javax.swing.JLabel lblLanches;
    private javax.swing.JLabel lblPizzas;
    private javax.swing.JTextArea painelDescAlimento;
    private javax.swing.JLabel painelDestaqueAlimento;
    private javax.swing.JPanel painelLanche;
    private javax.swing.JLabel painelPrecoAlimento;
    private javax.swing.JLabel painelTituloAlimento;
    private javax.swing.JScrollPane scrollCardapio;
    // End of variables declaration//GEN-END:variables

    public ControleMenu getC() {
        return c;
    }

    public void setC(ControleMenu c) {
        this.c = c;
    }

    public JButton getBtnAdicionar() {
        return btnAdicionar;
    }

    public void setBtnAdicionar(JButton btnAdicionar) {
        this.btnAdicionar = btnAdicionar;
    }

    public JButton getBtnGerarPedido() {
        return btnGerarPedido;
    }

    public void setBtnGerarPedido(JButton btnGerarPedido) {
        this.btnGerarPedido = btnGerarPedido;
    }

    public JButton getBtnVoltar() {
        return btnVoltar;
    }

    public void setBtnVoltar(JButton btnVoltar) {
        this.btnVoltar = btnVoltar;
    }

    public JLabel getImgBurguer11() {
        return imgBurguer11;
    }

    public void setImgBurguer11(JLabel imgBurguer11) {
        this.imgBurguer11 = imgBurguer11;
    }

    public JLabel getImgBurguer12() {
        return imgBurguer12;
    }

    public void setImgBurguer12(JLabel imgBurguer12) {
        this.imgBurguer12 = imgBurguer12;
    }

    public JLabel getImgBurguer13() {
        return imgBurguer13;
    }

    public void setImgBurguer13(JLabel imgBurguer13) {
        this.imgBurguer13 = imgBurguer13;
    }

    public JLabel getImgBurguer15() {
        return imgBurguer15;
    }

    public void setImgBurguer15(JLabel imgBurguer15) {
        this.imgBurguer15 = imgBurguer15;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return lblLanches;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.lblLanches = jLabel2;
    }

    public JScrollPane getjScrollPane1() {
        return scrollCardapio;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.scrollCardapio = jScrollPane1;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JTextArea getPainelDescAlimento() {
        return painelDescAlimento;
    }

    public void setPainelDescAlimento(JTextArea painelDescAlimento) {
        this.painelDescAlimento = painelDescAlimento;
    }

    public JLabel getPainelDestaqueAlimento() {
        return painelDestaqueAlimento;
    }

    public void setPainelDestaqueAlimento(JLabel painelDestaqueAlimento) {
        this.painelDestaqueAlimento = painelDestaqueAlimento;
    }

    public JPanel getPainelLanche() {
        return painelLanche;
    }

    public void setPainelLanche(JPanel painelLanche) {
        this.painelLanche = painelLanche;
    }

    public JLabel getPainelPrecoAlimento() {
        return painelPrecoAlimento;
    }

    public void setPainelPrecoAlimento(JLabel painelPrecoAlimento) {
        this.painelPrecoAlimento = painelPrecoAlimento;
    }

    public JLabel getPainelTituloAlimento() {
        return painelTituloAlimento;
    }

    public void setPainelTituloAlimento(JLabel painelTituloAlimento) {
        this.painelTituloAlimento = painelTituloAlimento;
    }

    
    
}
